services:
  bioclip-api:
    build: .
    image: bioclip-api:latest
    container_name: bioclip-server
    restart: unless-stopped
    ports:
      - "29844:8000"
    volumes:
      - ./models:/app/models
      - ./offline_images:/app/offline_images
      - ./bioclip.html:/app/bioclip.html
      - ./index.html:/app/index.html
      - ./kestrel.html:/app/kestrel.html  
      - ./publisher.html:/app/publisher.html
      - ./database:/app/database
      - ./app.py:/app/app.py

#     networks:
#       - 1panel-network

# networks:
#   1panel-network:
#     external: true

